---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Combine records when information is split across rows

Sometimes data for the same record is split across subsequent rows. This is particularly the case when you extract data from a PDF table using a tool like Tabula.

```{python}
# Setup
import numpy as np
import pandas as pd
```

## Create some sample data

In this data, it seems like the `message` value for the record with index 1 continues in the next row. However, there is no common identifier that can tie these rows together.

```{python}
raw_data = [
    ('1/2/2019', 'Facility 1', "A log message."),
    ('1/2/2019', 'Facility 1', "A longer log message "),
    (None, None, "that continues onto a second row."),
    ('1/3/2019', 'Facility 3', "Another log message."),
    
]
columns = ['date', 'facility', 'message']

data = pd.DataFrame.from_records(raw_data, columns=columns)

data
```

## Add an ID

We'll start by adding an arbitrary ID to each row. We can just use the index.

```{python}
data['id'] = data.index

data
```

## Remove the ID for rows that continue previous records

```{python}
data['id'] = np.where(pd.isna(data['date']), None, data['id'])

data
```

## Fill the now missing IDs with the ID of the previous record

After doing this, the continued record will share an ID with the row that has most of the rest of the information.

```{python}
data['id'] = data['id'].fillna(method='ffill')

data
```

## Use grouping and aggregation to merge the rows

We'll group by the synthetic ID that we created and then use the [form of the agg method that lets us specify separate aggregation functions for each column](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#applying-different-functions-to-dataframe-columns). I'm not entirely sure what the type of the data is that gets passed to the functions that are the values of the dictionary, but I think they're `Series`.

For the columns that don't continue on multiple rows, we use a lambda function that returns the value from the first row in the group. For the `message` column that is continued, we use the expression `' '.join`.

```{python}
data = data.groupby('id')\
    .agg({
        'date': lambda x: x.iloc[0],
        'facility': lambda x: x.iloc[0],
        'message': ' '.join,
    })

data
```

## Remove the temporary ID we used for grouping

```{python}
data = data.reset_index(drop=True)

data
```

```{python}

```
